### ISSUE TITLE
Validation tests using tplot sav files

### ISSUE THREAD

**Issue by ericthewizard** [spedas/pyspedas#455] opened 2023-04-27 17:49 UTC
I noticed that recent THEMIS validation tests use restored IDL sav files, downloaded from spedas.org, e.g., 

https://github.com/spedas/pyspedas/blob/master/pyspedas/themis/tests/tests_dsl_cotrans.py

I considered going this route early on, but there are some potential issues:

1. these files need to be maintained, since IDL SPEDAS is still under active development (https://spedas.org/changelog/). Every time a function being tested is updated in IDL, the test file should probably be updated as well (so this will likely get out of sync at some point)
2. only a few of us have access to spedas.org to update these files
3. testing updates to IDL SPEDAS require another test file to be built, then some version control for the test files

To avoid these issues, I built some tools to do validation tests using the `mgunit` framework; the tools can be found at:

https://github.com/spedas/pyspedas-validation

`mgunit` is distributed with IDL SPEDAS, so all SPEDAS users already have access to it. Here's a simple example of how it works:

https://github.com/spedas/pyspedas-validation/blob/main/src/example/validation_example_ut__define.pro

You implement simple test methods (that should start with `test_`), like any other `mgunit` test, and these methods:

1. load some tplot variables in IDL (using the users current version of IDL SPEDAS, so changing to a different version of IDL SPEDAS is simply a matter of updating the IDL paths)
2. implement a script to create the same tplot variables in PySPEDAS, as a list of strings
3. call `spd_run_py_validation` with the Python script and a list of tplot variables to check
4. the spd_run_py_validation function runs the Python script and then compares the tplot variables, to see if they're the same within some tolerance  (note: it only checks a few datapoints throughout, but this can be configured using the `points_to_check` keyword)

See:

https://github.com/spedas/pyspedas-validation/blob/main/src/common/spd_run_py_validation.pro

To run these tests in IDL, you do:

`IDL> mgunit, 'validation_example_ut'`

It's very kludgy (perhaps the most kludgy thing I've ever written), and I'm sure there are issues (like not being able to automatically run these in our GitHub Actions tests) but I think in the long run, it's probably better than maintaining large number of IDL sav files at spedas.org.

**Comment by jameswilburlewis** [comment] 2023-12-01 20:34
There is a need for both types of validation tests.   For example, mgunit-style testing cannot detect problems caused by changes to the data products at the providers' end (which seems to be a recurring issue with MMS).   We also need to improve the mgunit support, for example, to compare entire variables whatever their shape.   I'm going to close this issue, and address any tplot-sav or mgunit issues separately.

**Closed as not planned by jameswilburlewis** 2023-12-01 20:34 UTC
Labels: QA/Testing
