### ISSUE TITLE
Undesirable "merge" behavior in MAVEN and GOES load routines

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#916] opened 2024-07-01 20:39 UTC
When loading MAVEN data, load_data iterates through the CDF or STS files returned by the SDC request, then loads them one by one with merge=True.   This is probably not the best implementation, since users will probably expect existing tplot variables to be replaced, not appended, when a new request is being processed.

Similarly, in the GOES load() and loadr() routines, NetCDFs are loaded one-by-one with merge=True.

It would probably be better to process the entire list of CDF, NetCDF, or STS filenames in a single call, with merge=False as the default.

See also: https://github.com/spedas/pyspedas/issues/911

**Comment by nickssl** [comment] 2024-07-11 13:20
The problem was the underlying logic of the 'merge' keyword in netcdf_to_tplot. If merge=False, no merging was happening and this was by design. 

I have now changed the logic in netcdf_to_tplot. It should work like this:

1. All the data in the provided list of files will always be merged/combined, no matter what value the 'merge' keyword has.
2. If merge=False, the new data will replace any pre-existing tplot variables with the same names.
3. If merge=False, the new data will be merged with any pre-existing tplot variables with the same names.

**Comment by nickssl** [comment] 2024-08-19 22:04
The importer pytplot.sts_to_tplot used different logic for the 'merge' keyword. Now it is fixed and has the same behavior as the 'merge' keyword in cdf_to_tplot. 

So, 'merge' is now fixed for MAVEN, for cdf and sts files. 

MAVEN also imports other file types, like .tab files (mostly for kp data), but the code for these files has completely different inner workings and currently it does not use many of the keywords most other loading functions use (no prefix, suffix, merge). If we want to add merge (and also prefix and suffix) it will probably need a rewrite, perhaps adding a pytplot.tab_to_cdf importer.

**Closed** 2024-08-19 22:05 UTC
Labels: bug, pytplot, CDF, MAVEN
