### ISSUE TITLE
Dynamic spectra data not found in FIELDS

### ISSUE THREAD

**Issue by MohamedNedal** [spedas/pyspedas#124] opened 2022-01-25 10:54 UTC
Hello, How can I access the dynamic spectra data of radio emissions from the FIELDS instrument? 
I couldn't find a relevant keyword to radio emission spectra in `pyspedas.psp.fields `

**Comment by supervised** [comment] 2022-01-26 15:57
I'm assuming you're looking for the RFS data (e.g., PSP FIELDS datatypes: rfs_hfr, rfs_lfr, and rfs_burst). It looks like there was a regression that broke access to several of the FIELDS data types, including these - I'll check in a fix today, it should be available in pyspedas 1.3 (also going to be released later today).

**Comment by supervised** [comment] 2022-01-27 03:20
This should be fixed now! Here's a notebook I made using an example from the PSP team's IDL code:

https://colab.research.google.com/drive/1hWrS0IznDZX4qL_lkw8jQHFmrIzM2KIm?usp=sharing

**Closed** 2022-02-23 21:48 UTC
