### ISSUE TITLE
doesn't load in STATIC energy / phi / theta / etc data

### ISSUE THREAD

**Issue by NeeshaRS** [spedas/pyspedas#168] opened 2022-06-22 19:22 UTC
I was trying to use pyspedas to pull in STATIC data but I noticed large discrepancies in the data pulled by PySPEDAS vs pulling data in IDL. Looking at the CDF file, it seems like pyspedas is ignoring the file's metadata and just pulling variables/support variables. Unfortunately, for STATIC, important parameters (like energy, phi, theta, etc) are given in metadata rather than variables/support variables. 

Please enable reading in of the metadata parameters so STATIC data can be used to the full extent in python as well as in IDL.

Thank you!

**Comment by bryan-harter** [comment] 2022-06-22 19:32
I was looking over this with Neesa yesterday, and the problem is the Energy bins (labeled as "energy" inside the file) have an attribute VAR_TYPE of "metadata", rather than "data" or "support_data".  I assume that's actually a mistake within the STATIC files, because energy should definitely be considered "support_data".  But alas, there is no way they're going to change the file format at this point.  

The cdf_to_tplot routine assumes that all things labeled as metadata are either options to input into tplot (ylog, spec, title, etc), or they are not needed.  However in this case, we'd want to read in the metadata because its crucial to understanding the data in the file.  

As a quick fix, on the mpl and master branches of pytplot, I added a "get_metadata" option to the cdf_to_tplot routine so that it at least reads in the data so they can access the energy bins.  I'm not sure if there is a much better way of handling it, but that's what I've done for now.

**Comment by supervised** [comment] 2022-06-22 19:44
Thanks Bryan! I'll go ahead and update the STATIC routine to use the new keyword automatically (and release a new version of the MPL pytplot so it all just works)

**Comment by supervised** [comment] 2022-06-22 20:13
Oops - didn't mean to close this, though it should be fixed now as of v1.3.12

**Comment by NeeshaRS** [comment] 2022-06-23 14:15
Looks like the update broke something in pytplot...

**Comment by NeeshaRS** [comment] 2022-06-23 14:17
BUT the original problem we asked about does seem to have been fixed-- thank you!

**Comment by NeeshaRS** [comment] 2022-06-23 14:17
downloading static c0 data... <img width="514" alt="Screen Shot 2022-06-23 at 8 16 35 AM" src="https://user-images.githubusercontent.com/22404678/175321272-faeb2307-84a3-44fd-b27f-11d46a41d781.png">

**Comment by NeeshaRS** [comment] 2022-06-23 14:17
can now see variables of energy! :-D <img width="1019" alt="Screen Shot 2022-06-23 at 8 16 43 AM" src="https://user-images.githubusercontent.com/22404678/175321321-b4e9f7f6-d94d-4f8f-956d-9852bf6e9394.png">

**Comment by NeeshaRS** [comment] 2022-06-23 14:18
and the array looks reasonable at first glance. will dig in a bit more to better compare with what IDL pulls. <img width="655" alt="Screen Shot 2022-06-23 at 8 16 47 AM" src="https://user-images.githubusercontent.com/22404678/175321418-cd67fdaa-4bba-4539-a207-a8024439c31e.png">

**Comment by supervised** [comment] 2022-06-23 14:22
From the error, it looks like the eflux variable has too many dimensions. Is it a function of angle as well as energy?

One thing to note: in IDL SPEDAS, we have ~135k lines of code in the 'maven' folder alone, so there are many, many support routines that haven't been ported over yet just for MAVEN. It's possible that one of these routines does some calculations with these eflux variables prior to loading (e.g., averaging over angle) - but I haven't checked yet.

**Comment by juditbergfalk** [comment] 2022-06-23 17:36
I agree with @NeeshaRS, the original problem is fixed. Thank you for that! 
However, I keep getting a new error when running pytplot.tplot: "Problem with the number of line colors specified." and it doesn't open Tplot in a new window, rather in the notebook itself.
![image](https://user-images.githubusercontent.com/47789668/175360119-13e07585-494b-4d14-8014-dd368ec7bbcc.png)
The error code is not showing if I don't have any pytplot.options specificed (which I'll need) but the plots are still showing up in the notebook. I hope it's an easy fix!

**Comment by supervised** [comment] 2022-06-23 19:50
> I agree with @NeeshaRS, the original problem is fixed. Thank you for that! However, I keep getting a new error when running pytplot.tplot: "Problem with the number of line colors specified." and it doesn't open Tplot in a new window, rather in the notebook itself. ![image](https://user-images.githubusercontent.com/47789668/175360119-13e07585-494b-4d14-8014-dd368ec7bbcc.png) The error code is not showing if I don't have any pytplot.options specificed (which I'll need) but the plots are still showing up in the notebook. I hope it's an easy fix!

Do you have a simple example that would allow me to reproduce the problem?

**Comment by supervised** [comment] 2022-06-24 16:30
Thanks for the example! I just checked in a fix for the crash with `get_support_data=True` - I'll do another release of pytplot today to get this fix into PyPI. 

As for the error with colors: I don't think matplotlib supports the color format you're using for the SWIA T pseudo-variable :

`pytplot.options('MAVEN_SWIA_T_MSO', 'Color', [(69,117,180),(144,195,118),(215,48,39),(0,0,0)])`

When I try one of these on a normal tplot variable, I get the error:

 `ValueError: (69, 117, 180) is not a valid value for color`

Using the color formats specified in:

https://matplotlib.org/stable/tutorials/colors/colors.html

should fix the crash you're seeing; e.g., using:

`pytplot.options('MAVEN_SWIA_T_MSO', 'Color', ['purple', 'green', 'red', 'black'])`

worked for me. 

Hope this helps!

**Comment by supervised** [comment] 2022-06-24 19:20
What environment are you running in? If you're running it locally, so each call to pytplot.tplot will pause the script until you close the tplot window. Running inside a Jupyter notebook shouldn't have this issue. 

If you're running locally and want to create multiple plots without having to close the tplot window, I suggest setting the 'display' keyword to False and saving the figures using save_png (or save_svg/save_pdf/save_eps).  

I was able to run your script on Colab:

https://colab.research.google.com/drive/15_8696zPkkBBB4FKCuFvP8Y_cL35Oc92?usp=sharing

after changing the colors on the SWIA temp variable. 

Note: the 'slice' option to tplot also isn't implemented yet for the matplotlib version of pytplot.

**Comment by juditbergfalk** [comment] 2022-06-27 20:49
Thank you @NeeshaRS . I agree, a Zoom meeting would probably a good idea if you're available @supervised . I'm just a little bit confused because both the slice and the colors worked before the update.

**Comment by supervised** [comment] 2022-06-27 21:06
> Thank you @NeeshaRS . I agree, a Zoom meeting would probably a good idea if you're available @supervised . I'm just a little bit confused because both the slice and the colors worked before the update.

The backend to PyTplot (the entire part that renders figures) has been completely re-written from the ground up over the last 8 months; the version that comes with PySPEDAS now uses a completely different library internally (matplotlib vs. Qt previously). The slice keyword isn't there because it hasn't been implemented in the new version yet, and the color keyword doesn't accept the previous values because the way of specifying colors in matplotlib is different than Qt. You can find more information here:

https://github.com/MAVENSDC/PyTplot/issues/159

I'll look into adding the slice functionality back.

I can setup a Zoom meeting if you need, would you be available Thursday morning at 11AM Mountain time?

**Comment by supervised** [comment] 2022-06-29 22:15
> Oh okay, that makes sense now. Sorry for not understanding. I guess I should have updated it. I was really pleased to see the slice option and was even telling @NeeshaRS how cool of a tool it is to have so I'm looking forward to see that again but I understand if it'll be a lot of work! Thank you for your help and patience! I believe the zoom meeting won't be needed. I'll just keep an eye out for the updates.


The latest release of the matplotlib version of pytplot (v2.0.9 and later) now supports the 'slice' keyword; you can upgrade with:

pip install --upgrade pytplot-mpl-temp

Hope this helps!

**Closed** 2022-10-14 16:25 UTC
