### ISSUE TITLE
Specplot tests for different problematic data

### ISSUE THREAD

**Issue by jimm02** [spedas/pyspedas#787] opened 2024-03-04 20:15 UTC
This summarizes some problem specplots which are now working, using the specplot_resample_monotonic. Each example is associated with a correct plot, and can be used for regression testing.

import pyspedas
import pytplot
from pytplot import tplot

#ELFIN data with V values that oscillate, the original problem that resulted in the resample, this is an angular distrubtion
epd_var = pyspedas.elfin.epd(trange=['2021-07-14/11:55','2021-07-14/12:05'],probe='a',level='l2',type_='nflux',fullspin=False)
tplot('ela_pef_hs_nflux_ch0',display=False,save_png='ELFIN_test')

![ELFIN_test](https://github.com/spedas/pyspedas/assets/124631823/b612f329-8dcf-423a-ac7c-bb06f35384db)

#FAST TEAMS has fill values -1e31 in V, tod is an energy distribution, the bottom two are pitch angle distributions
teams_vars = pyspedas.fast.teams(['1998-09-05', '1998-09-06'])
tplot(['H+', 'H+_low', 'H+_high'], display=False, save_png='TEAMS_test')

![TEAMS_test](https://github.com/spedas/pyspedas/assets/124631823/2f913156-9ce3-4b45-8977-452919b0436a)

#THEMIS ESA has monotonically decreasing energies, time varying energies, and also has fill
esa_vars = pyspedas.themis.esa(trange=['2016-07-23','2016-07-24'],probe='a')
tplot('tha_peef_en_eflux', display=False, save_png='PEEF_test')

![PEEF_test](https://github.com/spedas/pyspedas/assets/124631823/7da4f9a5-4f5b-48c6-9bb8-8b1aae7b64d3)

#ERG specplots, only vertical lines on the bottom panel for original resample...
pyspedas.erg.hep(trange=['2017-03-27', '2017-03-28'])
tplot(['erg_hep_l2_FEDO_L', 'erg_hep_l2_FEDO_H'],display=False,save_png='ERG_test')

![ERG_test](https://github.com/spedas/pyspedas/assets/124631823/db24a8d7-2962-4ef5-a726-fc35fde18773)

**Comment by jimm02** [comment] 2024-03-04 20:17
Oops, Added the bad THEMIS ESA PEEF_test.png, Corrected:
![PEEF_test](https://github.com/spedas/pyspedas/assets/124631823/123f9a09-76a9-4c77-ba9a-be20eaa28148)

**Comment by jameswilburlewis** [comment] 2024-03-23 00:13
We might have a regression with the keogram plots.  With Y resampling enabled, the colors are mostly blue rather than mostly black.

```
from pyspedas import themis
from pytplot import store_data, options, timespan, tplot

# Set this to false for Github CI tests, set to True for interactive use to see plots.
global_display = False

ask_vars = themis.ask(trange=['2013-11-05', '2013-11-06'])
timespan('2013-11-05',1,'days')
# Should plot without errors, show something other than all-blue or vertical lines
tplot(['thg_ask_atha'],save_png='thg_ask_atha',display=global_display)
options('thg_ask_atha','y_no_resample',1)
tplot('thg_ask_atha', save_png='thg_ask_atha_no_resample',display=global_display)
timespan('2007-03-23',1,'days') # Reset to avoid interfering with other tests
```

With resampling:
![thg_ask_atha](https://github.com/spedas/pyspedas/assets/105754292/73c28029-2be3-494c-9a09-6845d32829b2)

Without resampling:
![thg_ask_atha_no_resample](https://github.com/spedas/pyspedas/assets/105754292/0fca1e6a-02d6-4e7d-9dc4-b4aa2d6f7b2b)

**Comment by jameswilburlewis** [comment] 2024-03-23 00:16
With the FAST TEAMS example, I get a slightly different plot.  For me, in the middle plot, it looks like the lower ylimit is 0, while in the example above it goes a little below 0.

![TEAMS_test](https://github.com/spedas/pyspedas/assets/105754292/7d993dfc-b224-440f-a473-1027ae388d56)

**Comment by jameswilburlewis** [comment] 2024-03-23 00:18
We now have a pyspedas test suite utilitites/tests/plot_tests.py containing all the above examples, and several others exercising plot options on pseudovariables.

**Comment by jameswilburlewis** [comment] 2024-03-23 16:50
The keogram regression is fixed now!  The patch to ensure that the upper and lower hi-res bin values were set properly didn't make it into the optimized version of specplot_resample.

**Comment by jameswilburlewis** [comment] 2024-03-23 18:25
The FAST pitch angle plots should be fixed now.  The center and bottom panels now have ymin of -90. (In the example plot above, the middle panel went to -90, but the bottom panel only went down to 0).

All the test cases seem to be working now, so I'll go ahead and close this issue.

**Comment by jameswilburlewis** [comment] 2024-03-23 20:30
Oops, still a couple more issues to look at...  First one is from Nick, with a case from MAVEN:

```
    def test_maven_specplot(self):
        from pyspedas.maven.spdf import load
        sta_vars = load(trange=['2020-12-30', '2020-12-31'], instrument='static', datatype='c0-64e2m')
        print(sta_vars)
        timespan('2020-12-30',1,'days')
        # This variable contains all zeroes, and is set to plot with log scaling
        tplot('bkg',display=global_display,save_png='MAVEN_test')
        timespan('2007-03-23',1,'days') # Reset to avoid interfering with other tests

```
This was originally showing a blank plot.  I saw what looked like a typo in specplot, where the plot zrange was being calculated with the min and max of the var_data.v.  I changed this to var_data.y, then it started crashing when adding the colormap to the plot.  In this variable var_data.y is all zeroes.  I guess matplotlib doesn't like vmin and vmax == 0 in the LogNorm call (even though the crash came later when creating the colorbar).    I changed that bit of code to this:

```
    if zlog == "log":
        zmin = np.nanmin(var_data.y)
        zmax = np.nanmax(var_data.y)
        # gracefully handle the case of all NaNs in the data, but log scale set
        # all 0 is also a problem, causes a crash later when creating the colorbar
        if np.isnan(var_data.y).all() or not np.any(var_data.y):
            # no need to set a log scale if all the data values are NaNs, or all zeroes
            spec_options["norm"] = None
            spec_options["vmin"] = zrange[0]
            spec_options["vmax"] = zrange[1]
        elif not np.any(var_data.y):
            # properly handle all 0s in the data   dead code now?
            spec_options["norm"] = mpl.colors.LogNorm(
                vmin=zmin, vmax=zmax
            )
        else:
            spec_options["norm"] = mpl.colors.LogNorm(vmin=zrange[0], vmax=zrange[1])
    else:
        spec_options["norm"] = None
        spec_options["vmin"] = zrange[0]
        spec_options["vmax"] = zrange[1]
``` 

So all 0 is now treated the same as all-NaN.   The plot comes out solid green now, with z range -0.1 to +0.1.  Is this what we want?
What about the case where zmin=zmax, but nonzero?



![Image](https://github.com/spedas/pyspedas/assets/105754292/b2204b19-d6d2-4214-b3f4-404fb8719d04)

**Comment by jameswilburlewis** [comment] 2024-03-23 20:47
Another MAVEN problem from Nick:

```
    def test_maven_fluxes_specplot(self):
        from pyspedas.maven.spdf import load
        swe_vars = load(trange=['2014-10-18', '2014-10-19'], instrument='swea')
        print(swe_vars)
        timespan('2014-10-18',1,'days')
        # This variable contains all zeroes, and is set to plot with log scaling
        tplot('diff_en_fluxes',display=global_display,save_png='MAVEN_fluxes_test')
        timespan('2007-03-23',1,'days') # Reset to avoid interfering with other tests

```

This crashes in  reduce_spec_dataset -- apparently spec_dim_to_tplot isn't set to anything.  Is there a sensible default?

```
  File "/Users/jwl/PycharmProjects/PyTplot/pytplot/tplot_utilities.py", line 718, in reduce_spec_dataset
    coordinate_to_plot = da.attrs['plot_options']['extras']['spec_dim_to_plot']
KeyError: 'spec_dim_to_plot'

```

**Comment by jameswilburlewis** [comment] 2024-03-26 18:23
The MAVEN diff_en_fluxes case turned out to have an interesting twist:  the variable is not marked in the CDF as a spectrogram.  Setting the "spec" option also sets the spec_dim_to_plot option (to "v2"' in this case".   Normally this would happen in cdf_to_tplot if it were marked as a spectrogram.  Manually setting spec_dim_to_plot to "v1" caused a crash because specplot only looked for "v", and not "v1" in that case (now fixed).  I changed reduce_spec_dataset to default to "v2" if spec_dim_to_plot isn't found, to match the default behavior in options.py.   So this plot and others like it should work now.

**Comment by jameswilburlewis** [comment] 2024-03-27 01:23
All the various scenarios described above now have passing tests in plot_tests.py, so we can close this issue.

**Closed by jameswilburlewis** 2024-03-27 01:23 UTC
Labels: bug, pytplot, plotting
