### ISSUE TITLE
tplot_restore does not restore data_att structure

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/pyspedas#439] opened 2023-04-10 19:22 UTC
See https://github.com/MAVENSDC/PyTplot/issues/174

Opening an issue here to track it in the SPEDAS project interface.

**Comment by supervised** [comment] 2023-04-14 17:49
Update: still looking into this, but it appears that this isn't simple (due to the output of scipy's readsav function, and the wide variety of potential metadata). At a minimum, we'll need plenty of regression tests for tplot_restore to ensure I'm not breaking anything with my changes.

**Comment by supervised** [comment] 2023-04-19 18:48
This one should be fixed in the bleeding edge now; I also added a test suite for tplot_restore

**Closed by supervised** 2023-04-19 18:48 UTC
Labels: bug, QA/Testing, pytplot

**Comment by jameswilburlewis** [comment] 2023-04-21 22:24
It seems to be working, thank you!
