### ISSUE TITLE
RBSP Hope file loading UnicodeDecodeError

### ISSUE THREAD

**Issue by kaltensi** [spedas/pyspedas#86] opened 2021-05-24 03:00 UTC
Trying to call pyspedas.rbsp.hope(trange = [date1, date2], probe = "a", datatype = "moments", level = "l3", notplot = True) throws a <class 'UnicodeDecodeError'> for SOME dates, but not all. For example, 2018-11-6 and 2018-11-9 fail but 2018-11-7 does not.
'ascii' codec can't decode byte 0xe0 in position 0: ordinal not in range(128).

I was using notplot = True to get a dictionary out, if that matters.

**Comment by supervised** [comment] 2021-05-30 20:00
Thanks for the report! We'll probably have to improve the error handling in the cdflib library to support these files. I updated my copy of cdflib to ignore (and simply continue on) when UnicodeDecodeError is thrown and those files loaded fine, so the string it's failing on doesn't seem important. 

I'll send a PR to cdflib that prints the error, but then continues on, so that we can support these files.

**Comment by horit** [comment] 2021-12-16 13:37
I just would like to know if there has been any progress on this? As you may know, some datasets of the Arase satellite have the same problem in which data-load modules crash and encounter the UnicodeDecodeError owing to some g/v-attributes in data files in CDF including non-ascii letters. As a workaround, currently the modules for Arase data use cdf_to_tplot() with the notplot option and then manually construct tplot variables. One big downside of this, however, is that none of g/v-attributes carries on into the tplot variables automatically.

**Comment by supervised** [comment] 2021-12-17 19:46
Sorry - I wasn't aware this was occurring in other places as well. I just submitted a PR with my fix, but I'm not sure how long it'll take to get into a release. 

In the mean time, could you update to my patched version and check if the Arase CDFs you were having trouble with load now? I'm not sure if ignoring the errors in the decoding process will allow you access to the global attributes..

Here's how to do the update to my patched version:

`pip install --upgrade https://github.com/supervised/cdflib/archive/master.zip`

**Comment by horit** [comment] 2021-12-21 09:22
Thank you so much for sharing the fixed version! cdf_to_tplot with the updated cdfread successfully reads CDF files of the Arase data and generates tplot variables with properly populated metadata now.

**Comment by horit** [comment] 2021-12-22 07:46
I just realized that the above command might skip updating the module, simply because the official tree and your forked one have the same version number at this point. Adding a couple of more options resolves the problem and you can update the cdflib module to the forked one: 
`pip install --upgrade --force-reinstall --no-deps https://github.com/supervised/cdflib/archive/master.zip`

**Comment by supervised** [comment] 2022-02-23 21:43
Just a heads up - there's a new release of cdflib out with this fix; I just confirmed the test case is working with the new release, so I'm going to go ahead and close this one. 

Thanks again for reporting this!

**Closed by supervised** 2022-02-23 21:43 UTC
